# Generated by Django 5.2.7 on 2025-10-15 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='招待メールアドレス')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='招待トークン')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='承認済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.company', verbose_name='招待先の会社')),
            ],
        ),
    ]
