# Generated by Django 5.2.7 on 2025-10-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'チェックリスト', 'verbose_name_plural': 'チェックリスト'},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'verbose_name': 'チェックリスト項目', 'verbose_name_plural': 'チェックリスト項目'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '会社', 'verbose_name_plural': '会社'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': '招待', 'verbose_name_plural': '招待'},
        ),
        migrations.AlterModelOptions(
            name='memo',
            options={'verbose_name': '共有メモ', 'verbose_name_plural': '共有メモ'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '案件', 'verbose_name_plural': '案件'},
        ),
    ]
