# Generated by Django 5.2.7 on 2025-10-16 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_checklist_options_alter_checklistitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='タスク名')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('progress', models.IntegerField(default=0, verbose_name='進捗率')),
                ('dependencies', models.ManyToManyField(blank=True, to='app.task', verbose_name='先行タスク')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': '工程タスク',
                'verbose_name_plural': '工程タスク',
            },
        ),
    ]
